---
#- hosts: all
#
#  vars:
#   packages:
#   #- docker*
#   - kubeadm
#   - kubectl
#   - kubelet

- name: Removendo repo Kubernetes.
  file:
   path: /etc/yum.repos.d/kubernetes.repo
   state: absent

#- name: Uninstalling kubernetes related packages
#  yum:
#   name: "{{ item }}"
#   state: absent
#  with_items: "{{ packages }}"
- name: Removendo config cluster antigo
  shell: kubeadm reset -f
  register: output

- name: Removendo arquivos
  file:
   path: "{{ item }}"
   state: absent
  with_items:
  - /etc/kubernetes/
  - /var/lib/etcd/
  - $HOME/.kube/

