#- import_playbook: playbooks/prerequisites.yml
#- import_playbook: playbooks/setting_up_nodes.yml
#- import_playbook: playbooks/configure_master_node.yml

#  Tarefas para serem executadas - Kubernetes 
- name: Criacao Cluster Kubernetes
  hosts: all
  vars_files:
#   - env_variables
   - /opt/web/ansible/production/k8s_cluster/vars/env_variables   
  remote_user: cmpdevops
#  remote_user: root
  gather_facts: no
  become: yes
  become_user: root
  tasks:
    - name: validando requisitos K8s
      include: pre-requisitos.yaml
    - name: playbook K8s
      include: setting_up_nodes.yaml


- name: Configuracao Kubernetes - Master
  hosts: master
  vars_files:
#   - env_variables
   - /opt/web/ansible/production/k8s_cluster/vars/env_variables   
  remote_user: cmpdevops
#  remote_user: root
  gather_facts: no
  become: yes
  become_user: root
  tasks:
    - name: playbook K8s
      include: configure_master.yaml  

- name: Adicionando workers ao Cluster Kubernetes
  hosts: worker
  vars_files:
#   - env_variables
   - /opt/web/ansible/production/k8s_cluster/vars/env_variables   
  remote_user: cmpdevops
#  remote_user: root
  gather_facts: no
  become: yes
  become_user: root
  tasks:
    - name: configure workers
      include: configure_worker.yaml
