---
#- hosts: all
##  vars_files:
##    - env_variables
##  remote_user: cmpdevops
##  gather_facts: false
##  tasks:
##   - name: Disabling swap on all nodes
##      shell: date
- name: Desabilitand Swap - Todas workers
  #vars_files: 
   # - env_variables
  shell: swapoff -a

- name: Comentando entrada Swap - /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '(.*swap*)'
    replace: '#\1'
